# Continuous Integration implementation
# MUCSCI 420
# Stephen Clugston and Josue Perez

name: SNEK Continuous Integration

on:
  push:
    branches: [ "ContinuousIntegration" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10 in enviornment
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Installing dependencies for tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        
    - name: Run tests using pytest
      run: |
        pytest