# Continuous Integration implementation
# MUCSCI 420
# Stephen Clugston and Josue Perez

name: SNEK Continuous Integration

on:
  push:
    branches: [ "ContinuousIntegration" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10 in enviornment
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Installing dependencies for tests and code coverage
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt
        pip install pytest-cov
        pytest --cov=./src/model --cov-report=xml
        
    - name: Run tests using pytest
      run: |
        pytest

    - name: Run code coverage using codecov
      uses: codecov/codecov-action@v3
      with: 
        token: ${{secrets.CODECOV_TOKEN}}
        fail_ci_if_error: true
        verbose: true
        coverage:
          round: down
          status:
            project:
              default:
                target: 80%