# Continuous Integration implementation
# MUCSCI 420
# Stephen Clugston and Josue Perez

name: Python application

on:
  push:
    branches: [ "ContinuousIntegration" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10 in enviornment
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        

    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
        
    - name: Lint using flake8
      run: |
        # Build exits = 1 if Python syntax errors or undefined names are found during the lint process
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test using pytest
      run: |
        pytest